### ISSUE TITLE
Cosmetica settings bugged when using In-game Account Switcher

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [Cosmetica-cc/Cosmetica#102]
**Describe the bug**
This bug makes cosmetics not show up on the player correctly when using the In-Game Account Switcher modification.

**To Reproduce**
1. Go to "In-Game Account Switcher" in Main Menu
2. Log in to other account
3. Go back and open Cosmetica settings
4. Cosmetics will now be displayed by the old player and / or cosmetics will be set to the old player when setting new cosmetics.

**Expected behavior**
Cosmetics should be displayed by the currently logged in player and should be set for this player.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 11 build 10.0.22631.1900
 - Minecraft Version: 1.20.1 with Quilt Loader 0.19.1
 - Version: 1.2.5

**Additional info/context**
This issue also applies to the Fabric version and is NOT an Quilt-only problem.
https://modrinth.com/mod/in-game-account-switcher required to reproduce.

**Comment by valoeghese** [comment]
I added some code for 1.2.6 that should make it detect account switches after a bit

**Comment by valoeghese** [comment]
Let us know on the discord if there are any further issues
