### ISSUE TITLE
says I have cosmetica, but I don't have cosmetica

### ISSUE THREAD

**Issue by ManInMyVan** [Cosmetica-cc/Cosmetica#104]
**Describe the bug**
says I have cosmetica, even though I don't.

**To Reproduce**
I don't know, it just happened.

**Expected behavior**
it should not say I have cosmetica.

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version 1.20.1

**Additional context**
So one time, a long time ago, I used this mod. I don't anymore, but it still says I have cosmetica to other cosmetica users. I do have a cloaksplus cape, and a minecraftcapes cape.

**Comment by eyezahhhh** [comment]
If you've used cosmetica before then you're in our database and other players will see you as a cosmetica user, this isn't a bug.

If you won't want to be seen as a cosmetica user then you can join our discord server https://cosmetica.cc/discord and we can delete your profile from our database.

**Comment by ManInMyVan** [comment]
What channel

**Comment by eyezahhhh** [comment]
#support
