### ISSUE TITLE
Skin Change Bug

### ISSUE THREAD

**Issue by LumiIsDead** [Cosmetica-cc/Cosmetica#106]
**Describe the bug**
Skin has not changed for 3 weeks. I cannot use Photobooth because of this.

**To Reproduce**
1. Get latest version of the mod.
2. Boot up Minecraft or go to website [cosmetica.cc]
3. Go to the profile.
4. See unchanged skin.

**Expected behavior**

**Screenshots**
The skin I use now:
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/111160282/36e9856a-e81b-429c-bb27-a860a8357d2a)

The skin I used before:
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/111160282/feab6b78-7364-46d2-8192-06c7a79e636e)

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version 1.20.1
 - Version: cosmetica-1.20-1.2.5.jar

**Comment by eyezahhhh** [comment]
3 weeks is far too long. What's your username?

**Comment by LumiIsDead** [comment]
LumiWasHere is my username. It has not changed.

**Comment by LumiIsDead** [comment]
It has now changed. It took way too long.
