### ISSUE TITLE
Can we self-host the backend server Cosmetica uses? Is it open-source?

### ISSUE THREAD

**Issue by jwaxy** [Cosmetica-cc/Cosmetica#108]
Title

**Comment by eyezahhhh** [comment]
The Cosmetica API is not open source. We have public libraries that use the api which you're free to use, but you can't self host it.

**Comment by jwaxy** [comment]
Ok. So, are you considering making it open source?

**Comment by eyezahhhh** [comment]
Not the current codebase, no. We're working on redesigning it though and we may reconsider open sourcing it when that's done, but no promises.
