### ISSUE TITLE
Cracked Account Error When I Don't Have A Cracked Account

### ISSUE THREAD

**Issue by C4liforniaRoll** [Cosmetica-cc/Cosmetica#109]
**Describe the bug**
Anytime I try to edit my cosmetics it comes up with an error message somewhere along the lines of 'internet connection is unstable, or you have a cracked account', which neither is true. I've been playing with Cosmetica perfectly fine for around a week and then noticed that my cosmetics disappeared, so I went to reactive them and got said error message after waiting for Cosmetica to load.

**To Reproduce**
I believe what might've happened was that I closed my laptop while my game and launcher were still going, and when I came back to it I saw in the launcher something along the lines of 'Purchases unable to load', however I've relaunched and relogged into my account multiple with no change.

**Screenshots**

The Error I keep getting
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/139183410/25de9f28-34db-4f02-a80c-c8a9487ed0b9)

Screenshot I took of myself wearing glasses from Cosmetica that I sent to friends a couple days prior to it not working
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/139183410/91961e56-d566-4f80-9e12-cddb91551af8)

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.2
 - Version: Cosmetica 1.2.5 for 1.19.1 and 1.19.2

**Comment by GrimmCrest** [comment]
how  was this problem solved? ive had the same issue on a server i recently started however it only effects me
