### ISSUE TITLE
couldnt authenticate account

### ISSUE THREAD

**Issue by zVort3X** [Cosmetica-cc/Cosmetica#115]
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/143902891/3b8fc998-ff44-43f7-aade-0a7fc9e42bc4)
I have fully paid for minecraft and have a premium account, im on feather fabric 1.19.4, it was working fine yesterday but now this shows, my internet if completely fine

**Comment by zVort3X** [comment]
I have 2 accounts linked 2 feather, i tried removing one but got the same error

**Comment by valoeghese** [comment]
Duplicate of #110
