### ISSUE TITLE
Cannot remove cape

### ISSUE THREAD

**Issue by corvidtowers** [Cosmetica-cc/Cosmetica#117]
**Describe the bug**
i've been attempting to remove my cape but it just keeps sticking to me, i cannot wear most back bling because it keeps putting the cape back on

**To Reproduce**
1. press customise cosmetics
2. put on back bling
3. go to capes
4. remove cape

**Expected behavior**
i had expected that the cape would be gone and id see my back bling

**Screenshots**
n/a

**Setup (please complete the following information):**
 - OS: windows 10
 - Minecraft Version: firefox?
 - Version: 1.18.2

**Additional context**
even the invisibble capes hide my back bling

**Comment by eyezahhhh** [comment]
Send a screenshot of the cape you're stuck wearing as well as your username. You can always disable your cape in skin customization settings.

**Comment by corvidtowers** [comment]
> Send a screenshot of the cape you're stuck wearing as well as your username. You can always disable your cape in skin customization settings.

i see. it was a me problem. sorry about that. im not smart
