### ISSUE TITLE
Enable own nametag affect 1st person

### ISSUE THREAD

**Issue by Julienraptor01** [Cosmetica-cc/Cosmetica#121]
**Describe the bug**
The option to see our own nametag in 3rd person also display it when in 1st person

**To Reproduce**
This cannot be seen easily unless you use a shader which then clearly show it since it cast a shadow
1. Enable a shader like Complementary with Iris
1. Enable the option and see the shadow of your nametag appear (place yourself properly so the sun cast a shadow on a wall or the ground)

**Expected behavior**
The nametag to only be enabled in 3rd person

**Screenshots**
With option enabled
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/49841713/9bf1841d-0720-4b74-b563-6c16f9932832)
Expected
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/49841713/dbe59ff0-c434-4b07-96b6-f4ca2f91ed7e)
Setting name in French
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/49841713/e5c577c2-b8c3-4cee-b45e-d01961b9fcb7)
Setting name in English
![image](https://github.com/Cosmetica-cc/Cosmetica/assets/49841713/089243ad-dc04-49e0-b055-1ef1b49ac836)

**Setup (please complete the following information):**
 - Minecraft : 1.19.2
 - Cosmetica : 1.2.5

**Additional context**
I actually set my game to English just to see and it seems like this button original wording is enable own nametag
So it might just have been a mistranslation
Despite that, i still think that nametag enabled in 1st person is unwanted behavior as you can't see it anyway

**Comment by valoeghese** [comment]
I thinik the french setting name is actually more accurate to what it's meant to be lol. The name of the setting in the `cosmetica.config` file is `show-nametag-in-third-person`, and in the code it's `showNametagInThirdPerson`.

Defo a bug
