### ISSUE TITLE
API blacklisted by avast

### ISSUE THREAD

**Issue by BirdNest055** [Cosmetica-cc/Cosmetica#123]
I cant start minecraft (Modpack DarkRPG) because avast blacklisted api.cosmetica.cc
![grafik](https://github.com/Cosmetica-cc/Cosmetica/assets/101951351/a8f63354-2074-4308-a451-ddd4832bc376)

**Comment by eyezahhhh** [comment]
Truly a bruh moment. Are you able to unblock it?

**Comment by BirdNest055** [comment]
I'd rather let the api maker request a white list for it than me lowering the safety of my pc.

**Comment by eyezahhhh** [comment]
Then you'll have to wait for a bit, we'll revisit this when we launch v2

**Comment by BirdNest055** [comment]
Thanks :D

**Comment by eyezahhhh** [comment]
For now just whitelist the domain or remove Cosmetica from your DarkRPG installation

**Comment by eyezahhhh** [comment]
Avast has removed our domain from the blacklist, it should work as normal
