### ISSUE TITLE
Minecraft crashes on launch

### ISSUE THREAD

**Issue by Erdef119** [Cosmetica-cc/Cosmetica#125]
**Describe the bug**
When i launch Minecraft with the mod, it crashes after the Minecraft window shows up. Without the mod, Minecraft works normally

**To Reproduce**
1. Launch Minecraft
2. See error

**Expected behavior**
Minecraft working normally

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10 Home 22H2
 - Minecraft Version: 1.19.3 Feather Fabric
 - Version 1.2.6-1.19.3

**Additional context**

Crash log: 
[latest.log](https://github.com/Cosmetica-cc/Cosmetica/files/13260842/latest.log)

**Comment by valoeghese** [comment]
This has been fixed as of 1.2.7
