### ISSUE TITLE
Random tutorial pop ups

### ISSUE THREAD

**Issue by Alfish9133** [Cosmetica-cc/Cosmetica#134]
Even after the force disabling of the tutorial announced on the discord, I keep getting the cosmetica tutorial every now and again, in game, seemingly after the servers come back online/work again after being down.

I don't think this could be intentionally replicated, I've tried a few things but can't get it to happen on command.

I didn't think to screenshot it until I saw others were having the same issue since the force disable, if I have it happen again I'll try to add a screenshot in an edit (if that's something doable on github)

 - OS: Windows 11
 - Minecraft Version: Quilt 0.23.0 1.20.1
 - Version: 1.2.7

~Edit 20:00 15/01~
I just got the tutorial again about 2 minutes ago, might just be specific to me somehow?

![Unable to determine world name 1 20 12024-01-15_19 53 38](https://github.com/Cosmetica-cc/Cosmetica/assets/139671424/d22e09d1-4ed6-4ba6-b4d6-22c25d4e5851)

~Edit 19:13 17/01~
Got it again, I'll keep adding more screenshots as I keep getting more tutorials 
![EthoQueens1 20 12024-01-17_19 12 12](https://github.com/Cosmetica-cc/Cosmetica/assets/139671424/03d76193-98c9-4aad-b34a-7fd59897a5bf)

~Edit 16:01 20/01~
Another one, this time the server still isn't up properly as I got it, maybe that isn't the common factor?
![EthoQueens1 20 12024-01-20_16 00 35](https://github.com/Cosmetica-cc/Cosmetica/assets/139671424/e5bfca75-543d-402f-a053-e43528da6088)

**Comment by LualtOfficial** [comment]
Should already be fixed

[valoeghese's discord message](https://discord.com/channels/942587512008888420/942589580996120576/1196166789109928076)
> I thought i turned it off 💀
> the mod should not be able to show the tutorial unless the server tells it to
> wait i might be dumb
> I only turned it off for if you were using an outdated version 😭💀
> it should work now
