### ISSUE TITLE
Update to 1.20.6 Please

### ISSUE THREAD

**Issue by sternschnaube** [Cosmetica-cc/Cosmetica#142]

**Comment by valoeghese** [comment]
Hello, a new version (1.2.10) is in progress which will release with a 1.20.6 version. In the meantime, you can compile the 1.20.6 branch of the repo yourself if you know how to

**Comment by sternschnaube** [comment]
Good to hear, building it worked for me, thanks 🥳

**Comment by valoeghese** [comment]
Released a 1.20.6 version just now
1.2.10 isn't complete, but I figured I'd get a 1.20.6 version out in the meantime anyway

**Comment by sternschnaube** [comment]
That's a good solution for the meantime.
