### ISSUE TITLE
"Error connecting to Cosmetica servers - We couldn't authenticate your account!" when using Curseforge Launcher

### ISSUE THREAD

**Issue by bvnniz** [Cosmetica-cc/Cosmetica#58]
![image](https://user-images.githubusercontent.com/111303383/189223609-a1f0ed7e-8d4c-4537-bdc4-73a88ed9b2a0.png)

I can't customize my character at all...! I know my internet is working because, well, I'm typing this.. lol... and I'm watching YouTube at the same time. Could it be because I'm using the Curseforge Launcher to play Minecraft? :(

**Comment by bvnniz** [comment]
okay, well.... turns out it was a specific "lore" option that would give that error... but nothing else would? weird

**Comment by eyezahhhh** [comment]
What was the lore option?

**Comment by bvnniz** [comment]
> What was the lore option?

sorry i literally forgot about this T_T the lore option in question was the very first in the list

![image](https://user-images.githubusercontent.com/111303383/192592680-6dcdb8e6-557f-477c-87f0-7922d87977de.png)

i just wanted the cute little face under my name 😅
