### ISSUE TITLE
When using Feather, the Feather doesn't appear

### ISSUE THREAD

**Issue by JoyousCreeper1059** [Cosmetica-cc/Cosmetica#65]
Normally when using Feather, you have a Feather icon above your head before your name, but when I use this mod, it disappears.

This is just a visual bug, and it still appears on the TAB list, but it's just easier to look at their nametag to see if they use Feather.

**Comment by BlockSwinger** [comment]
Don't use feather. Skidded, shitty and bloated version of fabric/forge that renders guis in chromium. No sane dev renders guis in chromium. Just switch to normal forge/fabric.

**Comment by eyezahhhh** [comment]
Regardless, if people use it. We'll try to support it (if it's not too much trouble). This problem occurs because our method for messing with nametags right now is fairly invasive. I've been told we may be able to change how we do this (which might fix the Feather issue), but we'll have to see.
