### ISSUE TITLE
I can't get into cosmetica.cc site.

### ISSUE THREAD

**Issue by CPTCroix** [Cosmetica-cc/Cosmetica#70]
It's been 15 minutes or so, but i still can't get into the site. Just... infinite loading screen.
![Untitled](https://user-images.githubusercontent.com/116356023/197187554-06575840-a25b-415a-94a8-9c4aa890fc51.png)

**Comment by Julienraptor01** [comment]
> It's been 15 minutes or so, but i still can't get into the site. Just... infinite loading screen.
> ![Untitled](https://user-images.githubusercontent.com/116356023/197187554-06575840-a25b-415a-94a8-9c4aa890fc51.png)
> 

Try to do ctrl+shift+r on the page

**Comment by CPTCroix** [comment]
Tried, nothing worked, decided to use another browser, worked perfectly fine. I guess forgot to enable hardware acceleration on Opera GX. But still, thanks for the help!

**Comment by eyezahhhh** [comment]
Closing due to website updates that make this issue outdated. If you still get this problem, let us know.
