### ISSUE TITLE
Lore title I need

### ISSUE THREAD

**Issue by TiboOpGithub** [Cosmetica-cc/Cosmetica#74]
Hi!

I was looking for a Lore text and saw that there was a title "2b2t player". Most of the time I play Minecraft I play on a popular Dutch server called Torchcraft. So it would be great if there could also be a title "Torchcraft player", a friend Mitsjol who also plays on the server with cosmetica thought it was a cool idea ;)

Tibo

**Comment by eyezahhhh** [comment]
Feel free to make a suggestion in our [Discord server](https://cosmetica.cc/discord), as that's where we track feature suggestions like lore requests.
