### ISSUE TITLE
Mod compatibility issues

### ISSUE THREAD

**Issue by kristofbolyai** [Cosmetica-cc/Cosmetica#75]
**Describe the bug**
[PlayerRenderMixin](https://github.com/Cosmetica-cc/Cosmetica/blob/1.18.1/src/main/java/cc/cosmetica/cosmetica/mixin/PlayerRendererMixin.java) makes the mod crash when used along any other mod that redirects / injects into and cancels `renderNameTag` (a pose will be left hanging in `PoseStack`, making the `checkPoseStack` fail in `LevelRenderer#renderLevel`).

**To Reproduce**
Install any mod that has the same mixin, like [Artemis](https://github.com/Wynntils/Artemis/blob/alpha/common/src/main/java/com/wynntils/mc/mixin/PlayerRendererMixin.java). 

**Expected behavior**
The mod should not crash.

**Additional context**
https://hst.sh/mosavokuca

**Comment by kristofbolyai** [comment]
A "simple" way to fix this would be to do the same thing I did, in [Artemis](https://github.com/Wynntils/Artemis/blob/alpha/common/src/main/java/com/wynntils/mc/mixin/PlayerRendererMixin.java). Yes, it is still bad from compatibility standpoint, and mods might render text over each other. BUT, will the mod crash? No, it won't. I think that is a fair compromise to make.

**Comment by valoeghese** [comment]
Another alternative might be to change the mixin priority so that other mixins run first, if the cancelling of renderNameTag happens at head. That way they cancel before our code even runs

**Comment by valoeghese** [comment]
I changed the priority to 2000 in dev, which should make it run after other mixins (the default priority is 1000, and higher priority runs later. See https://github.com/2xsaiko/mixin-cheatsheet/blob/master/mixin-priority.md)

**Comment by kristofbolyai** [comment]
> I changed the priority to 2000 in dev, which should make it run after other mixins (the default priority is 1000, and higher priority runs later. See https://github.com/2xsaiko/mixin-cheatsheet/blob/master/mixin-priority.md)

Well, that probably fixes it. Yeah, it is a weird fix, but probably the best we can do.

**Comment by kristofbolyai** [comment]
> that's what happens with higher priority. Greater priority makes it run later, according to that doc anyway. Don't worry: I also never remember which way around it is. I have to check the cheatsheet every time i mess with priority

It would be really weird that high priorities run later.

**Comment by valoeghese** [comment]
It isn't that weird if you consider that often the code that runs later gets the final say in what happens

**Comment by valoeghese** [comment]
Imagine you have three mixins that set the same field and don't cancel, all at the same location. It is the final mixin that gets the final say in setting the field

**Comment by valoeghese** [comment]
if it turns out that the doc is wrong and higher priority runs first, I'll change it again. I'll stick with the doc for now though

**Comment by kristofbolyai** [comment]
@valoeghese If you give me a jar, I can test it with Artemis (or you just put artemis as a mod in your dev env runs/mod folder)

**Comment by valoeghese** [comment]
If you want a jar lmk what version you're on

**Comment by kristofbolyai** [comment]
1.18.2. Have you had a release since this fix?

**Comment by valoeghese** [comment]
it should be fixed in the latest update

**Comment by valoeghese** [comment]
closing this issue as it should have been fixed
feel free to reopen if the issue persists
