### ISSUE TITLE
Incompatibiity with Model Gap Fix

### ISSUE THREAD

**Issue by valoeghese** [Cosmetica-cc/Cosmetica#77]
**Describe the bug**
ModelGapFix hooks in to one of the methods in `TextureAtlasSprite` to perform its function. It does a check for which texture atlas the sprite is using to know whether to apply its fixes, however we don't use a texture atlas on our `ModelSprite`s, so it throws UnsupportedOperationException.

**To Reproduce**
1. Download Cosmetica 1.2.2 and Model Gap Fix
2. Launch the game with both of them
3. Get the game to render a cosmetica player (for example: by opening the cosmetica gui)
4. Game crashes

**Expected behavior**

Dont crash

**Screenshots**
(see crash log from RaptaG in the discord)

**Setup (please complete the following information):**
 - OS: yes
 - Minecraft Version 1.19.3, but affects all
 - Version 1.2.2

**Additional context**
Fixed in development builds already by pretending to use the block atlas (will still crash when launched in a dev env as the original behaviour is useful for debug). This issue tracks it.

**Comment by eyezahhhh** [comment]
Fixed in 1.2.3.
