### ISSUE TITLE
optifine and cosmetica

### ISSUE THREAD

**Issue by miko340** [Cosmetica-cc/Cosmetica#78]
when i try to select hat 
minecraft starts to save the world(even if in menu)
and crashes

error

The game crashed whilst rendering fake player in menu
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1059.getShadersColorBlender(net.optifine.shaders.ShadersTextureType)" because "this.field_21750" is null

and it does not happen if optifine is not installed

Setup
 - OS: Windows 11
 - Minecraft Version 1.19.2
 - Version newest

**Comment by miko340** [comment]
shit i did not install arcmetica

**Comment by miko340** [comment]
nah still nothing

**Comment by eyezahhhh** [comment]
1.2.2 does not support OptiFine. If you must use OptiFine, then use Arcmetica instead of the fabric mod.
