### ISSUE TITLE
cant swtich mc accounts on the website

### ISSUE THREAD

**Issue by a-a3458** [Cosmetica-cc/Cosmetica#79]
**Describe the bug**
cant change profile on website 
**To Reproduce**
1. Go to '...' cosmetica website 
2. i dont see a way to change profiles of another account

**Expected behavior**
profiles to show me my other account
**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft java
 - Version 1.19

**Additional context**
website wont let you switch accounts

**Comment by eyezahhhh** [comment]
use [login.cosmetica.cc](https://login.cosmetica.cc) or sign into the website via the mod.
