### ISSUE TITLE
Arc Capes is listed on the website

### ISSUE THREAD

**Issue by Madis0** [Cosmetica-cc/Cosmetica#80]
**Describe the bug**
Cosmetica site mentions Arc Capes, despite it no longer existing.

**To Reproduce**
1. Go to https://cosmetica.cc
2. Click on ![](https://cosmetica.cc/page/logos/Arc.png)
3. See parked domain

**Expected behavior**
No logo, no link anywhere, to prevent confusing users

**Screenshots**
![image](https://user-images.githubusercontent.com/8611110/215125674-23517e26-23cb-4d31-94d1-8f397621b085.png)

**Setup (please complete the following information):**
N/A

**Additional context**
Imagine paying 511$ for a cape

**Comment by eyezahhhh** [comment]
You're right, the link hadn't been updated.

Arc's database lives on in Cosmetica.
