### ISSUE TITLE
[BUG] Equipping cosmetics with optifabric installed crashes the game.

### ISSUE THREAD

**Issue by Gingerail** [Cosmetica-cc/Cosmetica#82]
**Describe the bug**

**To Reproduce**
1. Load in with Optifabric and Cosmetica installed on fabric
2. Go into cosmetica
3. Attempt to equip any hat
4. The game crashes immediately

**Expected behavior**
Not crashing

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows 10]
 - Minecraft Version 1.19.2 Fabric

**Additional context**
After removing optifine and optifabric, the issue did not persist.

**Comment by eyezahhhh** [comment]
Unfortunately the latest version of Cosmetica makes no attempt to be compatible with OptiFabric and OptiFine. We may look at improving compatibility in future, but the closed-source nature of OptiFine makes this very difficult.

I'd recommend using alternatives to OptiFine if possible, a good list of such mods can be found [here](https://microcontrollersdev.github.io/Alternatives/latest/migrating/).

If you're in a situation where you _must_ use OptiFine (ie: you're using a very niche resource pack or PojavLauncher), then the best you can do is use [Arcmetica](https://cosmetica.cc/optifine). If you're using PojavLauncher, then this is built in and you just need to enable Cosmetica/Arcmetica in the launcher.
