### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Cosmetica-cc/Cosmetica#84]
**Describe the bug**
Minecraft crashes

**To Reproduce**
1. Go to server
2. crashes

**Expected behavior**
no crash

**Screenshots**

**Setup (please complete the following information):**
 - MacOS: 12.4
 - Minecraft Version: Quilt
 - Version 1.2.3

**Additional context**
I'm not entirely sure if it's this mod or a different mod. I just noticed it happened with this mod more frequently when enabled. When I disabled the mod it didn't happen as fast tho so maybe I'm wrong that its sole this mod

https://mclo.gs/TPAElBw

**Comment by valoeghese** [comment]
That crash is from a mod’s mixin to the `ThrownEnderPearl` class. We don’t do anything with thrown ender pearls so the crash isn’t us

**Comment by valoeghese** [comment]
Specifically it seems that some mod is crashing when an enderpearl lands on a creeper because it says the crash reason is mod tried to treat a Creeper as a Player

**Comment by Aces-and-Jacks** [comment]
ok, I think I might know. thanks

**Comment by Aces-and-Jacks** [comment]
actually not I don't know any that effect ender pearls but thanks anyway

**Comment by valoeghese** [comment]
my guess is one of your mods, although it doesn’t affect ender pearls, needs to do something under the hood when a pearl lands for some reason

**Comment by Aces-and-Jacks** [comment]
yeah. I don't really know how to reproduce the issue since it was in a server lobby at a specific time but I disabled a mod that I think may have been causing it. if the issue continues later I'll just figure it out from there
