### ISSUE TITLE
Crash when going through Cosmetica Menu [FABRIC]

### ISSUE THREAD

**Issue by Poke097** [Cosmetica-cc/Cosmetica#86]
**Describe the bug**

**To Reproduce**
1. Go to any menu
2. Click on click on anything
3. Crash

**Expected behavior**
To go through the menu without crashing.

**Crash Logs**
https://mclo.gs/QVy7qvY

**Setup (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version 1.19.2 Fabric Version: 0.14.17
 - Version Cosmetica 1.2.3 1.19.1

**Additional context**
It was a client side crash and it immediately did "Saving World" even though I wasn't in one.

**Comment by TrashV3** [comment]
I am also experiencing this issue and theres no way to change cosmetica settings or reset it after it bugs.

**Comment by eyezahhhh** [comment]
You can also change Cosmetica settings via the website in the meantime if menus become inaccessible.
