### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by Samisafool** [Cosmetica-cc/Cosmetica#88]
**Describe the bug**
It's not on 1.19.4, the latest MC version

**To Reproduce**
1. Try to download this mod/See it's raining
2. See it's not for 1.19.4/Cover yourself in oil
3. Weep/Fly

**Expected behavior**
It exists for 1.19.4

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Arch btw
 - Minecraft Version: 1.19.4
 - Version: Any

**Additional context**

**Comment by eyezahhhh** [comment]
This is not a bug report and you know it

**Comment by Samisafool** [comment]
Should I open a feature request then? I thought it was a bug, since "Dope Version Support" is one of the features and clearly it has a bug in it (aka no Dope Version Support).
