### ISSUE TITLE
Not working as a beta-version?

### ISSUE THREAD

**Issue by chloecdn** [Cosmetica-cc/Cosmetica#91]
**Describe the bug**
Mod not working in a beta-version. is this wanted behavior (for protecting the servers or similar) or a bug?

**To Reproduce**
1. Start the Game
2. Console saying `Cosmetica servers detected that you're rocking a beta version`
3. Error in console
4. Cosmetica-Settings aren't working.

**Expected behavior**
Welp... it's supposed to work i guess. lol.

**Screenshots**
Cosmetics are working:
![image](https://user-images.githubusercontent.com/80840951/233801214-10c3e7b6-a788-4b71-aaae-b1c2a7b55527.png)
Can't open the Settings:
![image](https://user-images.githubusercontent.com/80840951/233801261-954c4c60-8ad6-43c0-bad1-22eaf145912e.png)

**Setup (please complete the following information):**
 - OS: [Windows 11]
 - Minecraft Version [1.19.4]
 - Version [1.19.4 but doesnt seem to matter, as it's also present on the 1.18.2 master branch]

**Additional context**
It's failing to connect to the servers or something, i honestly have no idea.
It spits out the following error on startup:
```java
[20:41:09] [Cosmetica Authenticator #1/ERROR] (Cosmetica) Couldn't connect to cosmetica auth server
 java.lang.NullPointerException: Cannot invoke "cc.cosmetica.util.HostProvider.getSecureUrl()" because "this.apiHostProvider" is null
	at cc.cosmetica.impl.CosmeticaWebAPI.exchangeTokens(CosmeticaWebAPI.java:71) ~[CosmeticaDotJava-1.11.1.jar:?]
	at cc.cosmetica.impl.CosmeticaWebAPI.<init>(CosmeticaWebAPI.java:55) ~[CosmeticaDotJava-1.11.1.jar:?]
	at cc.cosmetica.impl.CosmeticaWebAPI.fromMinecraftToken(CosmeticaWebAPI.java:689) ~[CosmeticaDotJava-1.11.1.jar:?]
	at cc.cosmetica.api.CosmeticaAPI.fromMinecraftToken(CosmeticaAPI.java:481) ~[CosmeticaDotJava-1.11.1.jar:?]
	at cc.cosmetica.cosmetica.Authentication$1.run(Authentication.java:236) ~[main/:?]
```

The only thing that seems to be affected is the Settings-Screen, Cosmetics do work, and can be changed from the web-panel.
still it's kinda off, as everything else is actually working, so i don't think it's supposed to do this.

**Comment by eyezahhhh** [comment]
Building the mod yourself from GitHub is use-at-your-own-risk as between releases the branches often contain unfinished or improperly tested code. Once we're happy with the stability of the branches, we release to CurseForge and Modrinth ourselves.

This bug you encountered has already been caught by our beta testers and fixed. If you want to get access to "semi-stable" betas, join our [Discord server](https://cosmetica.cc/discord) and request to be a beta tester.

**Comment by valoeghese** [comment]
Building from source has is and has always been build-at-your-own-risk. This is a pretty good example as to why.

Did you build it 4-5 days ago? This bug was fixed in commit c8c55d34ab7440d4c467aa8352c05d7909fd96dc

**Comment by chloecdn** [comment]
ive built it about 20 minutes before opening this issue.
But yea, that was essentially the reason for opening this, so i can know if this is a bug, or not.

**Comment by chloecdn** [comment]
sorry for the late answer.

i just used intellij's `get from Version Control` feature, and then checked out both the master and 1.19.4-branches present at that moment.

maybe intellij did some weird stuff, no idea, don't know the mod-version anymore either, but it's fixed now in the official build anyway, so i guess this is "fixed" lol
